// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: handshake.proto

package com.fingerchat.proto.message;

public final class HandShake {
  private HandShake() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HandShakeMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HandShakeMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string deviceId = 1;</code>
     */
    String getDeviceId();
    /**
     * <code>string deviceId = 1;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    /**
     * <code>string osName = 2;</code>
     */
    String getOsName();
    /**
     * <code>string osName = 2;</code>
     */
    com.google.protobuf.ByteString
        getOsNameBytes();

    /**
     * <code>string osVersion = 3;</code>
     */
    String getOsVersion();
    /**
     * <code>string osVersion = 3;</code>
     */
    com.google.protobuf.ByteString
        getOsVersionBytes();

    /**
     * <code>string clientVersion = 4;</code>
     */
    String getClientVersion();
    /**
     * <code>string clientVersion = 4;</code>
     */
    com.google.protobuf.ByteString
        getClientVersionBytes();

    /**
     * <code>bytes iv = 5;</code>
     */
    com.google.protobuf.ByteString getIv();

    /**
     * <code>bytes clientKey = 6;</code>
     */
    com.google.protobuf.ByteString getClientKey();

    /**
     * <code>int32 minHeartbeat = 7;</code>
     */
    int getMinHeartbeat();

    /**
     * <code>int32 maxHeartbeat = 8;</code>
     */
    int getMaxHeartbeat();

    /**
     * <code>int64 timestamp = 9;</code>
     */
    long getTimestamp();

    /**
     * <code>string osModelType = 10;</code>
     */
    String getOsModelType();
    /**
     * <code>string osModelType = 10;</code>
     */
    com.google.protobuf.ByteString
        getOsModelTypeBytes();

    /**
     * <code>string terminalName = 11;</code>
     */
    String getTerminalName();
    /**
     * <code>string terminalName = 11;</code>
     */
    com.google.protobuf.ByteString
        getTerminalNameBytes();
  }
  /**
   * Protobuf type {@code HandShakeMessage}
   */
  public  static final class HandShakeMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HandShakeMessage)
      HandShakeMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HandShakeMessage.newBuilder() to construct.
    private HandShakeMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HandShakeMessage() {
      deviceId_ = "";
      osName_ = "";
      osVersion_ = "";
      clientVersion_ = "";
      iv_ = com.google.protobuf.ByteString.EMPTY;
      clientKey_ = com.google.protobuf.ByteString.EMPTY;
      minHeartbeat_ = 0;
      maxHeartbeat_ = 0;
      timestamp_ = 0L;
      osModelType_ = "";
      terminalName_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HandShakeMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              deviceId_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              osName_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              osVersion_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              clientVersion_ = s;
              break;
            }
            case 42: {

              iv_ = input.readBytes();
              break;
            }
            case 50: {

              clientKey_ = input.readBytes();
              break;
            }
            case 56: {

              minHeartbeat_ = input.readInt32();
              break;
            }
            case 64: {

              maxHeartbeat_ = input.readInt32();
              break;
            }
            case 72: {

              timestamp_ = input.readInt64();
              break;
            }
            case 82: {
              String s = input.readStringRequireUtf8();

              osModelType_ = s;
              break;
            }
            case 90: {
              String s = input.readStringRequireUtf8();

              terminalName_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HandShake.internal_static_HandShakeMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HandShake.internal_static_HandShakeMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HandShakeMessage.class, Builder.class);
    }

    public static final int DEVICEID_FIELD_NUMBER = 1;
    private volatile Object deviceId_;
    /**
     * <code>string deviceId = 1;</code>
     */
    public String getDeviceId() {
      Object ref = deviceId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      }
    }
    /**
     * <code>string deviceId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OSNAME_FIELD_NUMBER = 2;
    private volatile Object osName_;
    /**
     * <code>string osName = 2;</code>
     */
    public String getOsName() {
      Object ref = osName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        osName_ = s;
        return s;
      }
    }
    /**
     * <code>string osName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getOsNameBytes() {
      Object ref = osName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        osName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OSVERSION_FIELD_NUMBER = 3;
    private volatile Object osVersion_;
    /**
     * <code>string osVersion = 3;</code>
     */
    public String getOsVersion() {
      Object ref = osVersion_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        osVersion_ = s;
        return s;
      }
    }
    /**
     * <code>string osVersion = 3;</code>
     */
    public com.google.protobuf.ByteString
        getOsVersionBytes() {
      Object ref = osVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        osVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTVERSION_FIELD_NUMBER = 4;
    private volatile Object clientVersion_;
    /**
     * <code>string clientVersion = 4;</code>
     */
    public String getClientVersion() {
      Object ref = clientVersion_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        clientVersion_ = s;
        return s;
      }
    }
    /**
     * <code>string clientVersion = 4;</code>
     */
    public com.google.protobuf.ByteString
        getClientVersionBytes() {
      Object ref = clientVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        clientVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IV_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString iv_;
    /**
     * <code>bytes iv = 5;</code>
     */
    public com.google.protobuf.ByteString getIv() {
      return iv_;
    }

    public static final int CLIENTKEY_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString clientKey_;
    /**
     * <code>bytes clientKey = 6;</code>
     */
    public com.google.protobuf.ByteString getClientKey() {
      return clientKey_;
    }

    public static final int MINHEARTBEAT_FIELD_NUMBER = 7;
    private int minHeartbeat_;
    /**
     * <code>int32 minHeartbeat = 7;</code>
     */
    public int getMinHeartbeat() {
      return minHeartbeat_;
    }

    public static final int MAXHEARTBEAT_FIELD_NUMBER = 8;
    private int maxHeartbeat_;
    /**
     * <code>int32 maxHeartbeat = 8;</code>
     */
    public int getMaxHeartbeat() {
      return maxHeartbeat_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 9;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 9;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int OSMODELTYPE_FIELD_NUMBER = 10;
    private volatile Object osModelType_;
    /**
     * <code>string osModelType = 10;</code>
     */
    public String getOsModelType() {
      Object ref = osModelType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        osModelType_ = s;
        return s;
      }
    }
    /**
     * <code>string osModelType = 10;</code>
     */
    public com.google.protobuf.ByteString
        getOsModelTypeBytes() {
      Object ref = osModelType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        osModelType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TERMINALNAME_FIELD_NUMBER = 11;
    private volatile Object terminalName_;
    /**
     * <code>string terminalName = 11;</code>
     */
    public String getTerminalName() {
      Object ref = terminalName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        terminalName_ = s;
        return s;
      }
    }
    /**
     * <code>string terminalName = 11;</code>
     */
    public com.google.protobuf.ByteString
        getTerminalNameBytes() {
      Object ref = terminalName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        terminalName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDeviceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, deviceId_);
      }
      if (!getOsNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, osName_);
      }
      if (!getOsVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, osVersion_);
      }
      if (!getClientVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, clientVersion_);
      }
      if (!iv_.isEmpty()) {
        output.writeBytes(5, iv_);
      }
      if (!clientKey_.isEmpty()) {
        output.writeBytes(6, clientKey_);
      }
      if (minHeartbeat_ != 0) {
        output.writeInt32(7, minHeartbeat_);
      }
      if (maxHeartbeat_ != 0) {
        output.writeInt32(8, maxHeartbeat_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(9, timestamp_);
      }
      if (!getOsModelTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, osModelType_);
      }
      if (!getTerminalNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, terminalName_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDeviceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, deviceId_);
      }
      if (!getOsNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, osName_);
      }
      if (!getOsVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, osVersion_);
      }
      if (!getClientVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, clientVersion_);
      }
      if (!iv_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, iv_);
      }
      if (!clientKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, clientKey_);
      }
      if (minHeartbeat_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, minHeartbeat_);
      }
      if (maxHeartbeat_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, maxHeartbeat_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, timestamp_);
      }
      if (!getOsModelTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, osModelType_);
      }
      if (!getTerminalNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, terminalName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof HandShakeMessage)) {
        return super.equals(obj);
      }
      HandShakeMessage other = (HandShakeMessage) obj;

      boolean result = true;
      result = result && getDeviceId()
          .equals(other.getDeviceId());
      result = result && getOsName()
          .equals(other.getOsName());
      result = result && getOsVersion()
          .equals(other.getOsVersion());
      result = result && getClientVersion()
          .equals(other.getClientVersion());
      result = result && getIv()
          .equals(other.getIv());
      result = result && getClientKey()
          .equals(other.getClientKey());
      result = result && (getMinHeartbeat()
          == other.getMinHeartbeat());
      result = result && (getMaxHeartbeat()
          == other.getMaxHeartbeat());
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && getOsModelType()
          .equals(other.getOsModelType());
      result = result && getTerminalName()
          .equals(other.getTerminalName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceId().hashCode();
      hash = (37 * hash) + OSNAME_FIELD_NUMBER;
      hash = (53 * hash) + getOsName().hashCode();
      hash = (37 * hash) + OSVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getOsVersion().hashCode();
      hash = (37 * hash) + CLIENTVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getClientVersion().hashCode();
      hash = (37 * hash) + IV_FIELD_NUMBER;
      hash = (53 * hash) + getIv().hashCode();
      hash = (37 * hash) + CLIENTKEY_FIELD_NUMBER;
      hash = (53 * hash) + getClientKey().hashCode();
      hash = (37 * hash) + MINHEARTBEAT_FIELD_NUMBER;
      hash = (53 * hash) + getMinHeartbeat();
      hash = (37 * hash) + MAXHEARTBEAT_FIELD_NUMBER;
      hash = (53 * hash) + getMaxHeartbeat();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + OSMODELTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getOsModelType().hashCode();
      hash = (37 * hash) + TERMINALNAME_FIELD_NUMBER;
      hash = (53 * hash) + getTerminalName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static HandShakeMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HandShakeMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HandShakeMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HandShakeMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HandShakeMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HandShakeMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HandShakeMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HandShakeMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static HandShakeMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static HandShakeMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static HandShakeMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HandShakeMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(HandShakeMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HandShakeMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HandShakeMessage)
        HandShakeMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HandShake.internal_static_HandShakeMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HandShake.internal_static_HandShakeMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HandShakeMessage.class, Builder.class);
      }

      // Construct using com.fingerchat.proto.message.HandShake.HandShakeMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        deviceId_ = "";

        osName_ = "";

        osVersion_ = "";

        clientVersion_ = "";

        iv_ = com.google.protobuf.ByteString.EMPTY;

        clientKey_ = com.google.protobuf.ByteString.EMPTY;

        minHeartbeat_ = 0;

        maxHeartbeat_ = 0;

        timestamp_ = 0L;

        osModelType_ = "";

        terminalName_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HandShake.internal_static_HandShakeMessage_descriptor;
      }

      public HandShakeMessage getDefaultInstanceForType() {
        return HandShakeMessage.getDefaultInstance();
      }

      public HandShakeMessage build() {
        HandShakeMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public HandShakeMessage buildPartial() {
        HandShakeMessage result = new HandShakeMessage(this);
        result.deviceId_ = deviceId_;
        result.osName_ = osName_;
        result.osVersion_ = osVersion_;
        result.clientVersion_ = clientVersion_;
        result.iv_ = iv_;
        result.clientKey_ = clientKey_;
        result.minHeartbeat_ = minHeartbeat_;
        result.maxHeartbeat_ = maxHeartbeat_;
        result.timestamp_ = timestamp_;
        result.osModelType_ = osModelType_;
        result.terminalName_ = terminalName_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HandShakeMessage) {
          return mergeFrom((HandShakeMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(HandShakeMessage other) {
        if (other == HandShakeMessage.getDefaultInstance()) return this;
        if (!other.getDeviceId().isEmpty()) {
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (!other.getOsName().isEmpty()) {
          osName_ = other.osName_;
          onChanged();
        }
        if (!other.getOsVersion().isEmpty()) {
          osVersion_ = other.osVersion_;
          onChanged();
        }
        if (!other.getClientVersion().isEmpty()) {
          clientVersion_ = other.clientVersion_;
          onChanged();
        }
        if (other.getIv() != com.google.protobuf.ByteString.EMPTY) {
          setIv(other.getIv());
        }
        if (other.getClientKey() != com.google.protobuf.ByteString.EMPTY) {
          setClientKey(other.getClientKey());
        }
        if (other.getMinHeartbeat() != 0) {
          setMinHeartbeat(other.getMinHeartbeat());
        }
        if (other.getMaxHeartbeat() != 0) {
          setMaxHeartbeat(other.getMaxHeartbeat());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.getOsModelType().isEmpty()) {
          osModelType_ = other.osModelType_;
          onChanged();
        }
        if (!other.getTerminalName().isEmpty()) {
          terminalName_ = other.terminalName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        HandShakeMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (HandShakeMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object deviceId_ = "";
      /**
       * <code>string deviceId = 1;</code>
       */
      public String getDeviceId() {
        Object ref = deviceId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string deviceId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string deviceId = 1;</code>
       */
      public Builder setDeviceId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string deviceId = 1;</code>
       */
      public Builder clearDeviceId() {
        
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>string deviceId = 1;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceId_ = value;
        onChanged();
        return this;
      }

      private Object osName_ = "";
      /**
       * <code>string osName = 2;</code>
       */
      public String getOsName() {
        Object ref = osName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          osName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string osName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getOsNameBytes() {
        Object ref = osName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          osName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string osName = 2;</code>
       */
      public Builder setOsName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        osName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string osName = 2;</code>
       */
      public Builder clearOsName() {
        
        osName_ = getDefaultInstance().getOsName();
        onChanged();
        return this;
      }
      /**
       * <code>string osName = 2;</code>
       */
      public Builder setOsNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        osName_ = value;
        onChanged();
        return this;
      }

      private Object osVersion_ = "";
      /**
       * <code>string osVersion = 3;</code>
       */
      public String getOsVersion() {
        Object ref = osVersion_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          osVersion_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string osVersion = 3;</code>
       */
      public com.google.protobuf.ByteString
          getOsVersionBytes() {
        Object ref = osVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          osVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string osVersion = 3;</code>
       */
      public Builder setOsVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        osVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string osVersion = 3;</code>
       */
      public Builder clearOsVersion() {
        
        osVersion_ = getDefaultInstance().getOsVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string osVersion = 3;</code>
       */
      public Builder setOsVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        osVersion_ = value;
        onChanged();
        return this;
      }

      private Object clientVersion_ = "";
      /**
       * <code>string clientVersion = 4;</code>
       */
      public String getClientVersion() {
        Object ref = clientVersion_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          clientVersion_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string clientVersion = 4;</code>
       */
      public com.google.protobuf.ByteString
          getClientVersionBytes() {
        Object ref = clientVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          clientVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string clientVersion = 4;</code>
       */
      public Builder setClientVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string clientVersion = 4;</code>
       */
      public Builder clearClientVersion() {
        
        clientVersion_ = getDefaultInstance().getClientVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string clientVersion = 4;</code>
       */
      public Builder setClientVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientVersion_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString iv_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes iv = 5;</code>
       */
      public com.google.protobuf.ByteString getIv() {
        return iv_;
      }
      /**
       * <code>bytes iv = 5;</code>
       */
      public Builder setIv(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        iv_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes iv = 5;</code>
       */
      public Builder clearIv() {
        
        iv_ = getDefaultInstance().getIv();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString clientKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes clientKey = 6;</code>
       */
      public com.google.protobuf.ByteString getClientKey() {
        return clientKey_;
      }
      /**
       * <code>bytes clientKey = 6;</code>
       */
      public Builder setClientKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes clientKey = 6;</code>
       */
      public Builder clearClientKey() {
        
        clientKey_ = getDefaultInstance().getClientKey();
        onChanged();
        return this;
      }

      private int minHeartbeat_ ;
      /**
       * <code>int32 minHeartbeat = 7;</code>
       */
      public int getMinHeartbeat() {
        return minHeartbeat_;
      }
      /**
       * <code>int32 minHeartbeat = 7;</code>
       */
      public Builder setMinHeartbeat(int value) {
        
        minHeartbeat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 minHeartbeat = 7;</code>
       */
      public Builder clearMinHeartbeat() {
        
        minHeartbeat_ = 0;
        onChanged();
        return this;
      }

      private int maxHeartbeat_ ;
      /**
       * <code>int32 maxHeartbeat = 8;</code>
       */
      public int getMaxHeartbeat() {
        return maxHeartbeat_;
      }
      /**
       * <code>int32 maxHeartbeat = 8;</code>
       */
      public Builder setMaxHeartbeat(int value) {
        
        maxHeartbeat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 maxHeartbeat = 8;</code>
       */
      public Builder clearMaxHeartbeat() {
        
        maxHeartbeat_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 9;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 9;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 9;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private Object osModelType_ = "";
      /**
       * <code>string osModelType = 10;</code>
       */
      public String getOsModelType() {
        Object ref = osModelType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          osModelType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string osModelType = 10;</code>
       */
      public com.google.protobuf.ByteString
          getOsModelTypeBytes() {
        Object ref = osModelType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          osModelType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string osModelType = 10;</code>
       */
      public Builder setOsModelType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        osModelType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string osModelType = 10;</code>
       */
      public Builder clearOsModelType() {
        
        osModelType_ = getDefaultInstance().getOsModelType();
        onChanged();
        return this;
      }
      /**
       * <code>string osModelType = 10;</code>
       */
      public Builder setOsModelTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        osModelType_ = value;
        onChanged();
        return this;
      }

      private Object terminalName_ = "";
      /**
       * <code>string terminalName = 11;</code>
       */
      public String getTerminalName() {
        Object ref = terminalName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          terminalName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string terminalName = 11;</code>
       */
      public com.google.protobuf.ByteString
          getTerminalNameBytes() {
        Object ref = terminalName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          terminalName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string terminalName = 11;</code>
       */
      public Builder setTerminalName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        terminalName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string terminalName = 11;</code>
       */
      public Builder clearTerminalName() {
        
        terminalName_ = getDefaultInstance().getTerminalName();
        onChanged();
        return this;
      }
      /**
       * <code>string terminalName = 11;</code>
       */
      public Builder setTerminalNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        terminalName_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HandShakeMessage)
    }

    // @@protoc_insertion_point(class_scope:HandShakeMessage)
    private static final HandShakeMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new HandShakeMessage();
    }

    public static HandShakeMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HandShakeMessage>
        PARSER = new com.google.protobuf.AbstractParser<HandShakeMessage>() {
      public HandShakeMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HandShakeMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HandShakeMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<HandShakeMessage> getParserForType() {
      return PARSER;
    }

    public HandShakeMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HandshakeOkMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HandshakeOkMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes serverKey = 1;</code>
     */
    com.google.protobuf.ByteString getServerKey();

    /**
     * <code>int32 heartbeat = 2;</code>
     */
    int getHeartbeat();

    /**
     * <code>string sessionId = 3;</code>
     */
    String getSessionId();
    /**
     * <code>string sessionId = 3;</code>
     */
    com.google.protobuf.ByteString
        getSessionIdBytes();

    /**
     * <code>int64 expireTime = 4;</code>
     */
    long getExpireTime();
  }
  /**
   * Protobuf type {@code HandshakeOkMessage}
   */
  public  static final class HandshakeOkMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HandshakeOkMessage)
      HandshakeOkMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HandshakeOkMessage.newBuilder() to construct.
    private HandshakeOkMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HandshakeOkMessage() {
      serverKey_ = com.google.protobuf.ByteString.EMPTY;
      heartbeat_ = 0;
      sessionId_ = "";
      expireTime_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HandshakeOkMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              serverKey_ = input.readBytes();
              break;
            }
            case 16: {

              heartbeat_ = input.readInt32();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              sessionId_ = s;
              break;
            }
            case 32: {

              expireTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HandShake.internal_static_HandshakeOkMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HandShake.internal_static_HandshakeOkMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HandshakeOkMessage.class, Builder.class);
    }

    public static final int SERVERKEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString serverKey_;
    /**
     * <code>bytes serverKey = 1;</code>
     */
    public com.google.protobuf.ByteString getServerKey() {
      return serverKey_;
    }

    public static final int HEARTBEAT_FIELD_NUMBER = 2;
    private int heartbeat_;
    /**
     * <code>int32 heartbeat = 2;</code>
     */
    public int getHeartbeat() {
      return heartbeat_;
    }

    public static final int SESSIONID_FIELD_NUMBER = 3;
    private volatile Object sessionId_;
    /**
     * <code>string sessionId = 3;</code>
     */
    public String getSessionId() {
      Object ref = sessionId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      }
    }
    /**
     * <code>string sessionId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXPIRETIME_FIELD_NUMBER = 4;
    private long expireTime_;
    /**
     * <code>int64 expireTime = 4;</code>
     */
    public long getExpireTime() {
      return expireTime_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!serverKey_.isEmpty()) {
        output.writeBytes(1, serverKey_);
      }
      if (heartbeat_ != 0) {
        output.writeInt32(2, heartbeat_);
      }
      if (!getSessionIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sessionId_);
      }
      if (expireTime_ != 0L) {
        output.writeInt64(4, expireTime_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!serverKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, serverKey_);
      }
      if (heartbeat_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, heartbeat_);
      }
      if (!getSessionIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sessionId_);
      }
      if (expireTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, expireTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof HandshakeOkMessage)) {
        return super.equals(obj);
      }
      HandshakeOkMessage other = (HandshakeOkMessage) obj;

      boolean result = true;
      result = result && getServerKey()
          .equals(other.getServerKey());
      result = result && (getHeartbeat()
          == other.getHeartbeat());
      result = result && getSessionId()
          .equals(other.getSessionId());
      result = result && (getExpireTime()
          == other.getExpireTime());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERVERKEY_FIELD_NUMBER;
      hash = (53 * hash) + getServerKey().hashCode();
      hash = (37 * hash) + HEARTBEAT_FIELD_NUMBER;
      hash = (53 * hash) + getHeartbeat();
      hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + getSessionId().hashCode();
      hash = (37 * hash) + EXPIRETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getExpireTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static HandshakeOkMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HandshakeOkMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HandshakeOkMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HandshakeOkMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HandshakeOkMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HandshakeOkMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HandshakeOkMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HandshakeOkMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static HandshakeOkMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static HandshakeOkMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static HandshakeOkMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static HandshakeOkMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(HandshakeOkMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HandshakeOkMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HandshakeOkMessage)
        HandshakeOkMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HandShake.internal_static_HandshakeOkMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HandShake.internal_static_HandshakeOkMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HandshakeOkMessage.class, Builder.class);
      }

      // Construct using com.fingerchat.proto.message.HandShake.HandshakeOkMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        serverKey_ = com.google.protobuf.ByteString.EMPTY;

        heartbeat_ = 0;

        sessionId_ = "";

        expireTime_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HandShake.internal_static_HandshakeOkMessage_descriptor;
      }

      public HandshakeOkMessage getDefaultInstanceForType() {
        return HandshakeOkMessage.getDefaultInstance();
      }

      public HandshakeOkMessage build() {
        HandshakeOkMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public HandshakeOkMessage buildPartial() {
        HandshakeOkMessage result = new HandshakeOkMessage(this);
        result.serverKey_ = serverKey_;
        result.heartbeat_ = heartbeat_;
        result.sessionId_ = sessionId_;
        result.expireTime_ = expireTime_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HandshakeOkMessage) {
          return mergeFrom((HandshakeOkMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(HandshakeOkMessage other) {
        if (other == HandshakeOkMessage.getDefaultInstance()) return this;
        if (other.getServerKey() != com.google.protobuf.ByteString.EMPTY) {
          setServerKey(other.getServerKey());
        }
        if (other.getHeartbeat() != 0) {
          setHeartbeat(other.getHeartbeat());
        }
        if (!other.getSessionId().isEmpty()) {
          sessionId_ = other.sessionId_;
          onChanged();
        }
        if (other.getExpireTime() != 0L) {
          setExpireTime(other.getExpireTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        HandshakeOkMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (HandshakeOkMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString serverKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes serverKey = 1;</code>
       */
      public com.google.protobuf.ByteString getServerKey() {
        return serverKey_;
      }
      /**
       * <code>bytes serverKey = 1;</code>
       */
      public Builder setServerKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serverKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes serverKey = 1;</code>
       */
      public Builder clearServerKey() {
        
        serverKey_ = getDefaultInstance().getServerKey();
        onChanged();
        return this;
      }

      private int heartbeat_ ;
      /**
       * <code>int32 heartbeat = 2;</code>
       */
      public int getHeartbeat() {
        return heartbeat_;
      }
      /**
       * <code>int32 heartbeat = 2;</code>
       */
      public Builder setHeartbeat(int value) {
        
        heartbeat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 heartbeat = 2;</code>
       */
      public Builder clearHeartbeat() {
        
        heartbeat_ = 0;
        onChanged();
        return this;
      }

      private Object sessionId_ = "";
      /**
       * <code>string sessionId = 3;</code>
       */
      public String getSessionId() {
        Object ref = sessionId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          sessionId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string sessionId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSessionIdBytes() {
        Object ref = sessionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sessionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sessionId = 3;</code>
       */
      public Builder setSessionId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sessionId = 3;</code>
       */
      public Builder clearSessionId() {
        
        sessionId_ = getDefaultInstance().getSessionId();
        onChanged();
        return this;
      }
      /**
       * <code>string sessionId = 3;</code>
       */
      public Builder setSessionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sessionId_ = value;
        onChanged();
        return this;
      }

      private long expireTime_ ;
      /**
       * <code>int64 expireTime = 4;</code>
       */
      public long getExpireTime() {
        return expireTime_;
      }
      /**
       * <code>int64 expireTime = 4;</code>
       */
      public Builder setExpireTime(long value) {
        
        expireTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 expireTime = 4;</code>
       */
      public Builder clearExpireTime() {
        
        expireTime_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HandshakeOkMessage)
    }

    // @@protoc_insertion_point(class_scope:HandshakeOkMessage)
    private static final HandshakeOkMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new HandshakeOkMessage();
    }

    public static HandshakeOkMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HandshakeOkMessage>
        PARSER = new com.google.protobuf.AbstractParser<HandshakeOkMessage>() {
      public HandshakeOkMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HandshakeOkMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HandshakeOkMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<HandshakeOkMessage> getParserForType() {
      return PARSER;
    }

    public HandshakeOkMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HandShakeMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HandShakeMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HandshakeOkMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HandshakeOkMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017handshake.proto\"\347\001\n\020HandShakeMessage\022\020" +
      "\n\010deviceId\030\001 \001(\t\022\016\n\006osName\030\002 \001(\t\022\021\n\tosVe" +
      "rsion\030\003 \001(\t\022\025\n\rclientVersion\030\004 \001(\t\022\n\n\002iv" +
      "\030\005 \001(\014\022\021\n\tclientKey\030\006 \001(\014\022\024\n\014minHeartbea" +
      "t\030\007 \001(\005\022\024\n\014maxHeartbeat\030\010 \001(\005\022\021\n\ttimesta" +
      "mp\030\t \001(\003\022\023\n\013osModelType\030\n \001(\t\022\024\n\014termina" +
      "lName\030\013 \001(\t\"a\n\022HandshakeOkMessage\022\021\n\tser" +
      "verKey\030\001 \001(\014\022\021\n\theartbeat\030\002 \001(\005\022\021\n\tsessi" +
      "onId\030\003 \001(\t\022\022\n\nexpireTime\030\004 \001(\003B)\n\034com.fi" +
      "ngerchat.proto.messageB\tHandShakeb\006proto",
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_HandShakeMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HandShakeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HandShakeMessage_descriptor,
        new String[] { "DeviceId", "OsName", "OsVersion", "ClientVersion", "Iv", "ClientKey", "MinHeartbeat", "MaxHeartbeat", "Timestamp", "OsModelType", "TerminalName", });
    internal_static_HandshakeOkMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HandshakeOkMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HandshakeOkMessage_descriptor,
        new String[] { "ServerKey", "Heartbeat", "SessionId", "ExpireTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
