// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: muchat.proto

package com.fingerchat.proto.message;

public final class MucChat {
  private MucChat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RoomMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RoomMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.MessageType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>.MessageType type = 1;</code>
     */
    BaseChat.MessageType getType();

    /**
     * <pre>
     *发送消息者的用户名  userid--&gt;username
     * </pre>
     *
     * <code>string username = 2;</code>
     */
    String getUsername();
    /**
     * <pre>
     *发送消息者的用户名  userid--&gt;username
     * </pre>
     *
     * <code>string username = 2;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <pre>
     *roomid--&gt;mucid
     * </pre>
     *
     * <code>string mucid = 3;</code>
     */
    String getMucid();
    /**
     * <pre>
     *roomid--&gt;mucid
     * </pre>
     *
     * <code>string mucid = 3;</code>
     */
    com.google.protobuf.ByteString
        getMucidBytes();

    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string content = 4;</code>
     */
    String getContent();
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string content = 4;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>string id = 5;</code>
     */
    String getId();
    /**
     * <code>string id = 5;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>int32 code = 6;</code>
     */
    int getCode();

    /**
     * <code>int64 time = 7;</code>
     */
    long getTime();

    /**
     * <pre>
     *是否撤销  0：不撤销  1：撤销
     * </pre>
     *
     * <code>int32 cancel = 8;</code>
     */
    int getCancel();

    /**
     * <pre>
     * &#64;用户
     * </pre>
     *
     * <code>repeated .AtUser at = 9;</code>
     */
    java.util.List<AtUser>
        getAtList();
    /**
     * <pre>
     * &#64;用户
     * </pre>
     *
     * <code>repeated .AtUser at = 9;</code>
     */
    AtUser getAt(int index);
    /**
     * <pre>
     * &#64;用户
     * </pre>
     *
     * <code>repeated .AtUser at = 9;</code>
     */
    int getAtCount();
    /**
     * <pre>
     * &#64;用户
     * </pre>
     *
     * <code>repeated .AtUser at = 9;</code>
     */
    java.util.List<? extends AtUserOrBuilder>
        getAtOrBuilderList();
    /**
     * <pre>
     * &#64;用户
     * </pre>
     *
     * <code>repeated .AtUser at = 9;</code>
     */
    AtUserOrBuilder getAtOrBuilder(
        int index);

    /**
     * <pre>
     *是否&#64;所有人
     * </pre>
     *
     * <code>int32 atAll = 10;</code>
     */
    int getAtAll();
  }
  /**
   * Protobuf type {@code RoomMessage}
   */
  public  static final class RoomMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RoomMessage)
      RoomMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RoomMessage.newBuilder() to construct.
    private RoomMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RoomMessage() {
      type_ = 0;
      username_ = "";
      mucid_ = "";
      content_ = "";
      id_ = "";
      code_ = 0;
      time_ = 0L;
      cancel_ = 0;
      at_ = java.util.Collections.emptyList();
      atAll_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RoomMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              username_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              mucid_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 48: {

              code_ = input.readInt32();
              break;
            }
            case 56: {

              time_ = input.readInt64();
              break;
            }
            case 64: {

              cancel_ = input.readInt32();
              break;
            }
            case 74: {
              if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
                at_ = new java.util.ArrayList<AtUser>();
                mutable_bitField0_ |= 0x00000100;
              }
              at_.add(
                  input.readMessage(AtUser.parser(), extensionRegistry));
              break;
            }
            case 80: {

              atAll_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
          at_ = java.util.Collections.unmodifiableList(at_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MucChat.internal_static_RoomMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MucChat.internal_static_RoomMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RoomMessage.class, Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.MessageType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.MessageType type = 1;</code>
     */
    public BaseChat.MessageType getType() {
      BaseChat.MessageType result = BaseChat.MessageType.valueOf(type_);
      return result == null ? BaseChat.MessageType.UNRECOGNIZED : result;
    }

    public static final int USERNAME_FIELD_NUMBER = 2;
    private volatile Object username_;
    /**
     * <pre>
     *发送消息者的用户名  userid--&gt;username
     * </pre>
     *
     * <code>string username = 2;</code>
     */
    public String getUsername() {
      Object ref = username_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        username_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *发送消息者的用户名  userid--&gt;username
     * </pre>
     *
     * <code>string username = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MUCID_FIELD_NUMBER = 3;
    private volatile Object mucid_;
    /**
     * <pre>
     *roomid--&gt;mucid
     * </pre>
     *
     * <code>string mucid = 3;</code>
     */
    public String getMucid() {
      Object ref = mucid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        mucid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *roomid--&gt;mucid
     * </pre>
     *
     * <code>string mucid = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMucidBytes() {
      Object ref = mucid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        mucid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 4;
    private volatile Object content_;
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string content = 4;</code>
     */
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string content = 4;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 5;
    private volatile Object id_;
    /**
     * <code>string id = 5;</code>
     */
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 5;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CODE_FIELD_NUMBER = 6;
    private int code_;
    /**
     * <code>int32 code = 6;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int TIME_FIELD_NUMBER = 7;
    private long time_;
    /**
     * <code>int64 time = 7;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int CANCEL_FIELD_NUMBER = 8;
    private int cancel_;
    /**
     * <pre>
     *是否撤销  0：不撤销  1：撤销
     * </pre>
     *
     * <code>int32 cancel = 8;</code>
     */
    public int getCancel() {
      return cancel_;
    }

    public static final int AT_FIELD_NUMBER = 9;
    private java.util.List<AtUser> at_;
    /**
     * <pre>
     * &#64;用户
     * </pre>
     *
     * <code>repeated .AtUser at = 9;</code>
     */
    public java.util.List<AtUser> getAtList() {
      return at_;
    }
    /**
     * <pre>
     * &#64;用户
     * </pre>
     *
     * <code>repeated .AtUser at = 9;</code>
     */
    public java.util.List<? extends AtUserOrBuilder>
        getAtOrBuilderList() {
      return at_;
    }
    /**
     * <pre>
     * &#64;用户
     * </pre>
     *
     * <code>repeated .AtUser at = 9;</code>
     */
    public int getAtCount() {
      return at_.size();
    }
    /**
     * <pre>
     * &#64;用户
     * </pre>
     *
     * <code>repeated .AtUser at = 9;</code>
     */
    public AtUser getAt(int index) {
      return at_.get(index);
    }
    /**
     * <pre>
     * &#64;用户
     * </pre>
     *
     * <code>repeated .AtUser at = 9;</code>
     */
    public AtUserOrBuilder getAtOrBuilder(
        int index) {
      return at_.get(index);
    }

    public static final int ATALL_FIELD_NUMBER = 10;
    private int atAll_;
    /**
     * <pre>
     *是否&#64;所有人
     * </pre>
     *
     * <code>int32 atAll = 10;</code>
     */
    public int getAtAll() {
      return atAll_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != BaseChat.MessageType.TEXT.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!getUsernameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, username_);
      }
      if (!getMucidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, mucid_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, content_);
      }
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, id_);
      }
      if (code_ != 0) {
        output.writeInt32(6, code_);
      }
      if (time_ != 0L) {
        output.writeInt64(7, time_);
      }
      if (cancel_ != 0) {
        output.writeInt32(8, cancel_);
      }
      for (int i = 0; i < at_.size(); i++) {
        output.writeMessage(9, at_.get(i));
      }
      if (atAll_ != 0) {
        output.writeInt32(10, atAll_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != BaseChat.MessageType.TEXT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!getUsernameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, username_);
      }
      if (!getMucidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, mucid_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, content_);
      }
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, id_);
      }
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, code_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, time_);
      }
      if (cancel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, cancel_);
      }
      for (int i = 0; i < at_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, at_.get(i));
      }
      if (atAll_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, atAll_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RoomMessage)) {
        return super.equals(obj);
      }
      RoomMessage other = (RoomMessage) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && getUsername()
          .equals(other.getUsername());
      result = result && getMucid()
          .equals(other.getMucid());
      result = result && getContent()
          .equals(other.getContent());
      result = result && getId()
          .equals(other.getId());
      result = result && (getCode()
          == other.getCode());
      result = result && (getTime()
          == other.getTime());
      result = result && (getCancel()
          == other.getCancel());
      result = result && getAtList()
          .equals(other.getAtList());
      result = result && (getAtAll()
          == other.getAtAll());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUsername().hashCode();
      hash = (37 * hash) + MUCID_FIELD_NUMBER;
      hash = (53 * hash) + getMucid().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (37 * hash) + CANCEL_FIELD_NUMBER;
      hash = (53 * hash) + getCancel();
      if (getAtCount() > 0) {
        hash = (37 * hash) + AT_FIELD_NUMBER;
        hash = (53 * hash) + getAtList().hashCode();
      }
      hash = (37 * hash) + ATALL_FIELD_NUMBER;
      hash = (53 * hash) + getAtAll();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RoomMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RoomMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RoomMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RoomMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RoomMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RoomMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RoomMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RoomMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RoomMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RoomMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RoomMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RoomMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RoomMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RoomMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RoomMessage)
        RoomMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MucChat.internal_static_RoomMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MucChat.internal_static_RoomMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RoomMessage.class, Builder.class);
      }

      // Construct using com.fingerchat.proto.message.MucChat.RoomMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAtFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        username_ = "";

        mucid_ = "";

        content_ = "";

        id_ = "";

        code_ = 0;

        time_ = 0L;

        cancel_ = 0;

        if (atBuilder_ == null) {
          at_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
        } else {
          atBuilder_.clear();
        }
        atAll_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MucChat.internal_static_RoomMessage_descriptor;
      }

      public RoomMessage getDefaultInstanceForType() {
        return RoomMessage.getDefaultInstance();
      }

      public RoomMessage build() {
        RoomMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public RoomMessage buildPartial() {
        RoomMessage result = new RoomMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.type_ = type_;
        result.username_ = username_;
        result.mucid_ = mucid_;
        result.content_ = content_;
        result.id_ = id_;
        result.code_ = code_;
        result.time_ = time_;
        result.cancel_ = cancel_;
        if (atBuilder_ == null) {
          if (((bitField0_ & 0x00000100) == 0x00000100)) {
            at_ = java.util.Collections.unmodifiableList(at_);
            bitField0_ = (bitField0_ & ~0x00000100);
          }
          result.at_ = at_;
        } else {
          result.at_ = atBuilder_.build();
        }
        result.atAll_ = atAll_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RoomMessage) {
          return mergeFrom((RoomMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RoomMessage other) {
        if (other == RoomMessage.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getUsername().isEmpty()) {
          username_ = other.username_;
          onChanged();
        }
        if (!other.getMucid().isEmpty()) {
          mucid_ = other.mucid_;
          onChanged();
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (other.getCancel() != 0) {
          setCancel(other.getCancel());
        }
        if (atBuilder_ == null) {
          if (!other.at_.isEmpty()) {
            if (at_.isEmpty()) {
              at_ = other.at_;
              bitField0_ = (bitField0_ & ~0x00000100);
            } else {
              ensureAtIsMutable();
              at_.addAll(other.at_);
            }
            onChanged();
          }
        } else {
          if (!other.at_.isEmpty()) {
            if (atBuilder_.isEmpty()) {
              atBuilder_.dispose();
              atBuilder_ = null;
              at_ = other.at_;
              bitField0_ = (bitField0_ & ~0x00000100);
              atBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAtFieldBuilder() : null;
            } else {
              atBuilder_.addAllMessages(other.at_);
            }
          }
        }
        if (other.getAtAll() != 0) {
          setAtAll(other.getAtAll());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RoomMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RoomMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>.MessageType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.MessageType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.MessageType type = 1;</code>
       */
      public BaseChat.MessageType getType() {
        BaseChat.MessageType result = BaseChat.MessageType.valueOf(type_);
        return result == null ? BaseChat.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.MessageType type = 1;</code>
       */
      public Builder setType(BaseChat.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }

        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.MessageType type = 1;</code>
       */
      public Builder clearType() {

        type_ = 0;
        onChanged();
        return this;
      }

      private Object username_ = "";
      /**
       * <pre>
       *发送消息者的用户名  userid--&gt;username
       * </pre>
       *
       * <code>string username = 2;</code>
       */
      public String getUsername() {
        Object ref = username_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *发送消息者的用户名  userid--&gt;username
       * </pre>
       *
       * <code>string username = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发送消息者的用户名  userid--&gt;username
       * </pre>
       *
       * <code>string username = 2;</code>
       */
      public Builder setUsername(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送消息者的用户名  userid--&gt;username
       * </pre>
       *
       * <code>string username = 2;</code>
       */
      public Builder clearUsername() {

        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送消息者的用户名  userid--&gt;username
       * </pre>
       *
       * <code>string username = 2;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        username_ = value;
        onChanged();
        return this;
      }

      private Object mucid_ = "";
      /**
       * <pre>
       *roomid--&gt;mucid
       * </pre>
       *
       * <code>string mucid = 3;</code>
       */
      public String getMucid() {
        Object ref = mucid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          mucid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *roomid--&gt;mucid
       * </pre>
       *
       * <code>string mucid = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMucidBytes() {
        Object ref = mucid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          mucid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *roomid--&gt;mucid
       * </pre>
       *
       * <code>string mucid = 3;</code>
       */
      public Builder setMucid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        mucid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *roomid--&gt;mucid
       * </pre>
       *
       * <code>string mucid = 3;</code>
       */
      public Builder clearMucid() {

        mucid_ = getDefaultInstance().getMucid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *roomid--&gt;mucid
       * </pre>
       *
       * <code>string mucid = 3;</code>
       */
      public Builder setMucidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        mucid_ = value;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 4;</code>
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 4;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 4;</code>
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 4;</code>
       */
      public Builder clearContent() {

        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 4;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        content_ = value;
        onChanged();
        return this;
      }

      private Object id_ = "";
      /**
       * <code>string id = 5;</code>
       */
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string id = 5;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 5;</code>
       */
      public Builder setId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 5;</code>
       */
      public Builder clearId() {

        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 5;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        id_ = value;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <code>int32 code = 6;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>int32 code = 6;</code>
       */
      public Builder setCode(int value) {

        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 code = 6;</code>
       */
      public Builder clearCode() {

        code_ = 0;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <code>int64 time = 7;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>int64 time = 7;</code>
       */
      public Builder setTime(long value) {

        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 time = 7;</code>
       */
      public Builder clearTime() {

        time_ = 0L;
        onChanged();
        return this;
      }

      private int cancel_ ;
      /**
       * <pre>
       *是否撤销  0：不撤销  1：撤销
       * </pre>
       *
       * <code>int32 cancel = 8;</code>
       */
      public int getCancel() {
        return cancel_;
      }
      /**
       * <pre>
       *是否撤销  0：不撤销  1：撤销
       * </pre>
       *
       * <code>int32 cancel = 8;</code>
       */
      public Builder setCancel(int value) {

        cancel_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否撤销  0：不撤销  1：撤销
       * </pre>
       *
       * <code>int32 cancel = 8;</code>
       */
      public Builder clearCancel() {

        cancel_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<AtUser> at_ =
        java.util.Collections.emptyList();
      private void ensureAtIsMutable() {
        if (!((bitField0_ & 0x00000100) == 0x00000100)) {
          at_ = new java.util.ArrayList<AtUser>(at_);
          bitField0_ |= 0x00000100;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          AtUser, AtUser.Builder, AtUserOrBuilder> atBuilder_;

      /**
       * <pre>
       * &#64;用户
       * </pre>
       *
       * <code>repeated .AtUser at = 9;</code>
       */
      public java.util.List<AtUser> getAtList() {
        if (atBuilder_ == null) {
          return java.util.Collections.unmodifiableList(at_);
        } else {
          return atBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * &#64;用户
       * </pre>
       *
       * <code>repeated .AtUser at = 9;</code>
       */
      public int getAtCount() {
        if (atBuilder_ == null) {
          return at_.size();
        } else {
          return atBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * &#64;用户
       * </pre>
       *
       * <code>repeated .AtUser at = 9;</code>
       */
      public AtUser getAt(int index) {
        if (atBuilder_ == null) {
          return at_.get(index);
        } else {
          return atBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * &#64;用户
       * </pre>
       *
       * <code>repeated .AtUser at = 9;</code>
       */
      public Builder setAt(
          int index, AtUser value) {
        if (atBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAtIsMutable();
          at_.set(index, value);
          onChanged();
        } else {
          atBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * &#64;用户
       * </pre>
       *
       * <code>repeated .AtUser at = 9;</code>
       */
      public Builder setAt(
          int index, AtUser.Builder builderForValue) {
        if (atBuilder_ == null) {
          ensureAtIsMutable();
          at_.set(index, builderForValue.build());
          onChanged();
        } else {
          atBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * &#64;用户
       * </pre>
       *
       * <code>repeated .AtUser at = 9;</code>
       */
      public Builder addAt(AtUser value) {
        if (atBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAtIsMutable();
          at_.add(value);
          onChanged();
        } else {
          atBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * &#64;用户
       * </pre>
       *
       * <code>repeated .AtUser at = 9;</code>
       */
      public Builder addAt(
          int index, AtUser value) {
        if (atBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAtIsMutable();
          at_.add(index, value);
          onChanged();
        } else {
          atBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * &#64;用户
       * </pre>
       *
       * <code>repeated .AtUser at = 9;</code>
       */
      public Builder addAt(
          AtUser.Builder builderForValue) {
        if (atBuilder_ == null) {
          ensureAtIsMutable();
          at_.add(builderForValue.build());
          onChanged();
        } else {
          atBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * &#64;用户
       * </pre>
       *
       * <code>repeated .AtUser at = 9;</code>
       */
      public Builder addAt(
          int index, AtUser.Builder builderForValue) {
        if (atBuilder_ == null) {
          ensureAtIsMutable();
          at_.add(index, builderForValue.build());
          onChanged();
        } else {
          atBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * &#64;用户
       * </pre>
       *
       * <code>repeated .AtUser at = 9;</code>
       */
      public Builder addAllAt(
          Iterable<? extends AtUser> values) {
        if (atBuilder_ == null) {
          ensureAtIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, at_);
          onChanged();
        } else {
          atBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * &#64;用户
       * </pre>
       *
       * <code>repeated .AtUser at = 9;</code>
       */
      public Builder clearAt() {
        if (atBuilder_ == null) {
          at_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
          onChanged();
        } else {
          atBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * &#64;用户
       * </pre>
       *
       * <code>repeated .AtUser at = 9;</code>
       */
      public Builder removeAt(int index) {
        if (atBuilder_ == null) {
          ensureAtIsMutable();
          at_.remove(index);
          onChanged();
        } else {
          atBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * &#64;用户
       * </pre>
       *
       * <code>repeated .AtUser at = 9;</code>
       */
      public AtUser.Builder getAtBuilder(
          int index) {
        return getAtFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * &#64;用户
       * </pre>
       *
       * <code>repeated .AtUser at = 9;</code>
       */
      public AtUserOrBuilder getAtOrBuilder(
          int index) {
        if (atBuilder_ == null) {
          return at_.get(index);  } else {
          return atBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * &#64;用户
       * </pre>
       *
       * <code>repeated .AtUser at = 9;</code>
       */
      public java.util.List<? extends AtUserOrBuilder>
           getAtOrBuilderList() {
        if (atBuilder_ != null) {
          return atBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(at_);
        }
      }
      /**
       * <pre>
       * &#64;用户
       * </pre>
       *
       * <code>repeated .AtUser at = 9;</code>
       */
      public AtUser.Builder addAtBuilder() {
        return getAtFieldBuilder().addBuilder(
            AtUser.getDefaultInstance());
      }
      /**
       * <pre>
       * &#64;用户
       * </pre>
       *
       * <code>repeated .AtUser at = 9;</code>
       */
      public AtUser.Builder addAtBuilder(
          int index) {
        return getAtFieldBuilder().addBuilder(
            index, AtUser.getDefaultInstance());
      }
      /**
       * <pre>
       * &#64;用户
       * </pre>
       *
       * <code>repeated .AtUser at = 9;</code>
       */
      public java.util.List<AtUser.Builder>
           getAtBuilderList() {
        return getAtFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          AtUser, AtUser.Builder, AtUserOrBuilder>
          getAtFieldBuilder() {
        if (atBuilder_ == null) {
          atBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              AtUser, AtUser.Builder, AtUserOrBuilder>(
                  at_,
                  ((bitField0_ & 0x00000100) == 0x00000100),
                  getParentForChildren(),
                  isClean());
          at_ = null;
        }
        return atBuilder_;
      }

      private int atAll_ ;
      /**
       * <pre>
       *是否&#64;所有人
       * </pre>
       *
       * <code>int32 atAll = 10;</code>
       */
      public int getAtAll() {
        return atAll_;
      }
      /**
       * <pre>
       *是否&#64;所有人
       * </pre>
       *
       * <code>int32 atAll = 10;</code>
       */
      public Builder setAtAll(int value) {

        atAll_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否&#64;所有人
       * </pre>
       *
       * <code>int32 atAll = 10;</code>
       */
      public Builder clearAtAll() {

        atAll_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RoomMessage)
    }

    // @@protoc_insertion_point(class_scope:RoomMessage)
    private static final RoomMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RoomMessage();
    }

    public static RoomMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RoomMessage>
        PARSER = new com.google.protobuf.AbstractParser<RoomMessage>() {
      public RoomMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RoomMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RoomMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RoomMessage> getParserForType() {
      return PARSER;
    }

    public RoomMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AtUserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AtUser)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *用户名
     * </pre>
     *
     * <code>string username = 1;</code>
     */
    String getUsername();
    /**
     * <pre>
     *用户名
     * </pre>
     *
     * <code>string username = 1;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <pre>
     *昵称
     * </pre>
     *
     * <code>string usernick = 2;</code>
     */
    String getUsernick();
    /**
     * <pre>
     *昵称
     * </pre>
     *
     * <code>string usernick = 2;</code>
     */
    com.google.protobuf.ByteString
        getUsernickBytes();
  }
  /**
   * Protobuf type {@code AtUser}
   */
  public  static final class AtUser extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AtUser)
      AtUserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AtUser.newBuilder() to construct.
    private AtUser(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AtUser() {
      username_ = "";
      usernick_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AtUser(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              username_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              usernick_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MucChat.internal_static_AtUser_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MucChat.internal_static_AtUser_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AtUser.class, Builder.class);
    }

    public static final int USERNAME_FIELD_NUMBER = 1;
    private volatile Object username_;
    /**
     * <pre>
     *用户名
     * </pre>
     *
     * <code>string username = 1;</code>
     */
    public String getUsername() {
      Object ref = username_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        username_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *用户名
     * </pre>
     *
     * <code>string username = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERNICK_FIELD_NUMBER = 2;
    private volatile Object usernick_;
    /**
     * <pre>
     *昵称
     * </pre>
     *
     * <code>string usernick = 2;</code>
     */
    public String getUsernick() {
      Object ref = usernick_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        usernick_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *昵称
     * </pre>
     *
     * <code>string usernick = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUsernickBytes() {
      Object ref = usernick_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        usernick_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUsernameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, username_);
      }
      if (!getUsernickBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, usernick_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUsernameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, username_);
      }
      if (!getUsernickBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, usernick_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AtUser)) {
        return super.equals(obj);
      }
      AtUser other = (AtUser) obj;

      boolean result = true;
      result = result && getUsername()
          .equals(other.getUsername());
      result = result && getUsernick()
          .equals(other.getUsernick());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUsername().hashCode();
      hash = (37 * hash) + USERNICK_FIELD_NUMBER;
      hash = (53 * hash) + getUsernick().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AtUser parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AtUser parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AtUser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AtUser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AtUser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AtUser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AtUser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AtUser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AtUser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AtUser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AtUser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AtUser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AtUser prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AtUser}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AtUser)
        AtUserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MucChat.internal_static_AtUser_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MucChat.internal_static_AtUser_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AtUser.class, Builder.class);
      }

      // Construct using com.fingerchat.proto.message.MucChat.AtUser.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        username_ = "";

        usernick_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MucChat.internal_static_AtUser_descriptor;
      }

      public AtUser getDefaultInstanceForType() {
        return AtUser.getDefaultInstance();
      }

      public AtUser build() {
        AtUser result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public AtUser buildPartial() {
        AtUser result = new AtUser(this);
        result.username_ = username_;
        result.usernick_ = usernick_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AtUser) {
          return mergeFrom((AtUser)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AtUser other) {
        if (other == AtUser.getDefaultInstance()) return this;
        if (!other.getUsername().isEmpty()) {
          username_ = other.username_;
          onChanged();
        }
        if (!other.getUsernick().isEmpty()) {
          usernick_ = other.usernick_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AtUser parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AtUser) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object username_ = "";
      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>string username = 1;</code>
       */
      public String getUsername() {
        Object ref = username_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>string username = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>string username = 1;</code>
       */
      public Builder setUsername(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>string username = 1;</code>
       */
      public Builder clearUsername() {

        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户名
       * </pre>
       *
       * <code>string username = 1;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        username_ = value;
        onChanged();
        return this;
      }

      private Object usernick_ = "";
      /**
       * <pre>
       *昵称
       * </pre>
       *
       * <code>string usernick = 2;</code>
       */
      public String getUsernick() {
        Object ref = usernick_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          usernick_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *昵称
       * </pre>
       *
       * <code>string usernick = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUsernickBytes() {
        Object ref = usernick_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          usernick_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *昵称
       * </pre>
       *
       * <code>string usernick = 2;</code>
       */
      public Builder setUsernick(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        usernick_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *昵称
       * </pre>
       *
       * <code>string usernick = 2;</code>
       */
      public Builder clearUsernick() {

        usernick_ = getDefaultInstance().getUsernick();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *昵称
       * </pre>
       *
       * <code>string usernick = 2;</code>
       */
      public Builder setUsernickBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        usernick_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AtUser)
    }

    // @@protoc_insertion_point(class_scope:AtUser)
    private static final AtUser DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AtUser();
    }

    public static AtUser getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AtUser>
        PARSER = new com.google.protobuf.AbstractParser<AtUser>() {
      public AtUser parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AtUser(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AtUser> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AtUser> getParserForType() {
      return PARSER;
    }

    public AtUser getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoomMessage_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoomMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AtUser_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AtUser_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014muchat.proto\032\nchat.proto\"\267\001\n\013RoomMessa" +
      "ge\022\032\n\004type\030\001 \001(\0162\014.MessageType\022\020\n\010userna" +
      "me\030\002 \001(\t\022\r\n\005mucid\030\003 \001(\t\022\017\n\007content\030\004 \001(\t" +
      "\022\n\n\002id\030\005 \001(\t\022\014\n\004code\030\006 \001(\005\022\014\n\004time\030\007 \001(\003" +
      "\022\016\n\006cancel\030\010 \001(\005\022\023\n\002at\030\t \003(\0132\007.AtUser\022\r\n" +
      "\005atAll\030\n \001(\005\",\n\006AtUser\022\020\n\010username\030\001 \001(\t" +
      "\022\020\n\010usernick\030\002 \001(\tB\'\n\034com.fingerchat.pro" +
      "to.messageB\007MucChatb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          BaseChat.getDescriptor(),
        }, assigner);
    internal_static_RoomMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RoomMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoomMessage_descriptor,
        new String[] { "Type", "Username", "Mucid", "Content", "Id", "Code", "Time", "Cancel", "At", "AtAll", });
    internal_static_AtUser_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AtUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AtUser_descriptor,
        new String[] { "Username", "Usernick", });
    BaseChat.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
