// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: readack.proto

package com.fingerchat.proto.message;

public final class ReadAck {
  private ReadAck() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReadedMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReadedMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *0 或者空 表示来自他人  1  来自自己另外客户端的同步已读  (客户端向服务器推送可以为空)
     * </pre>
     *
     * <code>int32 synchro = 1;</code>
     */
    int getSynchro();

    /**
     * <pre>
     *已读的那条消息  的接收人(推送已读消息的推送人  客户端向服务器推送可以为空)
     * </pre>
     *
     * <code>string to = 2;</code>
     */
    String getTo();
    /**
     * <pre>
     *已读的那条消息  的接收人(推送已读消息的推送人  客户端向服务器推送可以为空)
     * </pre>
     *
     * <code>string to = 2;</code>
     */
    com.google.protobuf.ByteString
        getToBytes();

    /**
     * <pre>
     *已读的那条消息  的发送人
     * </pre>
     *
     * <code>string from = 3;</code>
     */
    String getFrom();
    /**
     * <pre>
     *已读的那条消息  的发送人
     * </pre>
     *
     * <code>string from = 3;</code>
     */
    com.google.protobuf.ByteString
        getFromBytes();

    /**
     * <pre>
     *已读的那条消息的  消息ID
     * </pre>
     *
     * <code>string oid = 4;</code>
     */
    String getOid();
    /**
     * <pre>
     *已读的那条消息的  消息ID
     * </pre>
     *
     * <code>string oid = 4;</code>
     */
    com.google.protobuf.ByteString
        getOidBytes();

    /**
     * <pre>
     *当前消息id  可以为空
     * </pre>
     *
     * <code>string id = 5;</code>
     */
    String getId();
    /**
     * <pre>
     *当前消息id  可以为空
     * </pre>
     *
     * <code>string id = 5;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <pre>
     *群id
     * </pre>
     *
     * <code>string mucId = 6;</code>
     */
    String getMucId();
    /**
     * <pre>
     *群id
     * </pre>
     *
     * <code>string mucId = 6;</code>
     */
    com.google.protobuf.ByteString
        getMucIdBytes();
  }
  /**
   * Protobuf type {@code ReadedMessage}
   */
  public  static final class ReadedMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ReadedMessage)
      ReadedMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReadedMessage.newBuilder() to construct.
    private ReadedMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReadedMessage() {
      synchro_ = 0;
      to_ = "";
      from_ = "";
      oid_ = "";
      id_ = "";
      mucId_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReadedMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              synchro_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              to_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              from_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              oid_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              mucId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ReadAck.internal_static_ReadedMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ReadAck.internal_static_ReadedMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ReadedMessage.class, Builder.class);
    }

    public static final int SYNCHRO_FIELD_NUMBER = 1;
    private int synchro_;
    /**
     * <pre>
     *0 或者空 表示来自他人  1  来自自己另外客户端的同步已读  (客户端向服务器推送可以为空)
     * </pre>
     *
     * <code>int32 synchro = 1;</code>
     */
    public int getSynchro() {
      return synchro_;
    }

    public static final int TO_FIELD_NUMBER = 2;
    private volatile Object to_;
    /**
     * <pre>
     *已读的那条消息  的接收人(推送已读消息的推送人  客户端向服务器推送可以为空)
     * </pre>
     *
     * <code>string to = 2;</code>
     */
    public String getTo() {
      Object ref = to_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        to_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *已读的那条消息  的接收人(推送已读消息的推送人  客户端向服务器推送可以为空)
     * </pre>
     *
     * <code>string to = 2;</code>
     */
    public com.google.protobuf.ByteString
        getToBytes() {
      Object ref = to_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROM_FIELD_NUMBER = 3;
    private volatile Object from_;
    /**
     * <pre>
     *已读的那条消息  的发送人
     * </pre>
     *
     * <code>string from = 3;</code>
     */
    public String getFrom() {
      Object ref = from_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        from_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *已读的那条消息  的发送人
     * </pre>
     *
     * <code>string from = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFromBytes() {
      Object ref = from_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        from_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OID_FIELD_NUMBER = 4;
    private volatile Object oid_;
    /**
     * <pre>
     *已读的那条消息的  消息ID
     * </pre>
     *
     * <code>string oid = 4;</code>
     */
    public String getOid() {
      Object ref = oid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        oid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *已读的那条消息的  消息ID
     * </pre>
     *
     * <code>string oid = 4;</code>
     */
    public com.google.protobuf.ByteString
        getOidBytes() {
      Object ref = oid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        oid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 5;
    private volatile Object id_;
    /**
     * <pre>
     *当前消息id  可以为空
     * </pre>
     *
     * <code>string id = 5;</code>
     */
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *当前消息id  可以为空
     * </pre>
     *
     * <code>string id = 5;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MUCID_FIELD_NUMBER = 6;
    private volatile Object mucId_;
    /**
     * <pre>
     *群id
     * </pre>
     *
     * <code>string mucId = 6;</code>
     */
    public String getMucId() {
      Object ref = mucId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        mucId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *群id
     * </pre>
     *
     * <code>string mucId = 6;</code>
     */
    public com.google.protobuf.ByteString
        getMucIdBytes() {
      Object ref = mucId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        mucId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (synchro_ != 0) {
        output.writeInt32(1, synchro_);
      }
      if (!getToBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, to_);
      }
      if (!getFromBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, from_);
      }
      if (!getOidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, oid_);
      }
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, id_);
      }
      if (!getMucIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, mucId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (synchro_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, synchro_);
      }
      if (!getToBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, to_);
      }
      if (!getFromBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, from_);
      }
      if (!getOidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, oid_);
      }
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, id_);
      }
      if (!getMucIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, mucId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ReadedMessage)) {
        return super.equals(obj);
      }
      ReadedMessage other = (ReadedMessage) obj;

      boolean result = true;
      result = result && (getSynchro()
          == other.getSynchro());
      result = result && getTo()
          .equals(other.getTo());
      result = result && getFrom()
          .equals(other.getFrom());
      result = result && getOid()
          .equals(other.getOid());
      result = result && getId()
          .equals(other.getId());
      result = result && getMucId()
          .equals(other.getMucId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SYNCHRO_FIELD_NUMBER;
      hash = (53 * hash) + getSynchro();
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + getTo().hashCode();
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + getFrom().hashCode();
      hash = (37 * hash) + OID_FIELD_NUMBER;
      hash = (53 * hash) + getOid().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + MUCID_FIELD_NUMBER;
      hash = (53 * hash) + getMucId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ReadedMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReadedMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReadedMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReadedMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReadedMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReadedMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReadedMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ReadedMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ReadedMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ReadedMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ReadedMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ReadedMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ReadedMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReadedMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReadedMessage)
        ReadedMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ReadAck.internal_static_ReadedMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ReadAck.internal_static_ReadedMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ReadedMessage.class, Builder.class);
      }

      // Construct using com.fingerchat.proto.message.ReadAck.ReadedMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        synchro_ = 0;

        to_ = "";

        from_ = "";

        oid_ = "";

        id_ = "";

        mucId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ReadAck.internal_static_ReadedMessage_descriptor;
      }

      public ReadedMessage getDefaultInstanceForType() {
        return ReadedMessage.getDefaultInstance();
      }

      public ReadedMessage build() {
        ReadedMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ReadedMessage buildPartial() {
        ReadedMessage result = new ReadedMessage(this);
        result.synchro_ = synchro_;
        result.to_ = to_;
        result.from_ = from_;
        result.oid_ = oid_;
        result.id_ = id_;
        result.mucId_ = mucId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ReadedMessage) {
          return mergeFrom((ReadedMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ReadedMessage other) {
        if (other == ReadedMessage.getDefaultInstance()) return this;
        if (other.getSynchro() != 0) {
          setSynchro(other.getSynchro());
        }
        if (!other.getTo().isEmpty()) {
          to_ = other.to_;
          onChanged();
        }
        if (!other.getFrom().isEmpty()) {
          from_ = other.from_;
          onChanged();
        }
        if (!other.getOid().isEmpty()) {
          oid_ = other.oid_;
          onChanged();
        }
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getMucId().isEmpty()) {
          mucId_ = other.mucId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ReadedMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ReadedMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int synchro_ ;
      /**
       * <pre>
       *0 或者空 表示来自他人  1  来自自己另外客户端的同步已读  (客户端向服务器推送可以为空)
       * </pre>
       *
       * <code>int32 synchro = 1;</code>
       */
      public int getSynchro() {
        return synchro_;
      }
      /**
       * <pre>
       *0 或者空 表示来自他人  1  来自自己另外客户端的同步已读  (客户端向服务器推送可以为空)
       * </pre>
       *
       * <code>int32 synchro = 1;</code>
       */
      public Builder setSynchro(int value) {
        
        synchro_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *0 或者空 表示来自他人  1  来自自己另外客户端的同步已读  (客户端向服务器推送可以为空)
       * </pre>
       *
       * <code>int32 synchro = 1;</code>
       */
      public Builder clearSynchro() {
        
        synchro_ = 0;
        onChanged();
        return this;
      }

      private Object to_ = "";
      /**
       * <pre>
       *已读的那条消息  的接收人(推送已读消息的推送人  客户端向服务器推送可以为空)
       * </pre>
       *
       * <code>string to = 2;</code>
       */
      public String getTo() {
        Object ref = to_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          to_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *已读的那条消息  的接收人(推送已读消息的推送人  客户端向服务器推送可以为空)
       * </pre>
       *
       * <code>string to = 2;</code>
       */
      public com.google.protobuf.ByteString
          getToBytes() {
        Object ref = to_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          to_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *已读的那条消息  的接收人(推送已读消息的推送人  客户端向服务器推送可以为空)
       * </pre>
       *
       * <code>string to = 2;</code>
       */
      public Builder setTo(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *已读的那条消息  的接收人(推送已读消息的推送人  客户端向服务器推送可以为空)
       * </pre>
       *
       * <code>string to = 2;</code>
       */
      public Builder clearTo() {
        
        to_ = getDefaultInstance().getTo();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *已读的那条消息  的接收人(推送已读消息的推送人  客户端向服务器推送可以为空)
       * </pre>
       *
       * <code>string to = 2;</code>
       */
      public Builder setToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        to_ = value;
        onChanged();
        return this;
      }

      private Object from_ = "";
      /**
       * <pre>
       *已读的那条消息  的发送人
       * </pre>
       *
       * <code>string from = 3;</code>
       */
      public String getFrom() {
        Object ref = from_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          from_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *已读的那条消息  的发送人
       * </pre>
       *
       * <code>string from = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFromBytes() {
        Object ref = from_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          from_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *已读的那条消息  的发送人
       * </pre>
       *
       * <code>string from = 3;</code>
       */
      public Builder setFrom(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *已读的那条消息  的发送人
       * </pre>
       *
       * <code>string from = 3;</code>
       */
      public Builder clearFrom() {
        
        from_ = getDefaultInstance().getFrom();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *已读的那条消息  的发送人
       * </pre>
       *
       * <code>string from = 3;</code>
       */
      public Builder setFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        from_ = value;
        onChanged();
        return this;
      }

      private Object oid_ = "";
      /**
       * <pre>
       *已读的那条消息的  消息ID
       * </pre>
       *
       * <code>string oid = 4;</code>
       */
      public String getOid() {
        Object ref = oid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          oid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *已读的那条消息的  消息ID
       * </pre>
       *
       * <code>string oid = 4;</code>
       */
      public com.google.protobuf.ByteString
          getOidBytes() {
        Object ref = oid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          oid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *已读的那条消息的  消息ID
       * </pre>
       *
       * <code>string oid = 4;</code>
       */
      public Builder setOid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        oid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *已读的那条消息的  消息ID
       * </pre>
       *
       * <code>string oid = 4;</code>
       */
      public Builder clearOid() {
        
        oid_ = getDefaultInstance().getOid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *已读的那条消息的  消息ID
       * </pre>
       *
       * <code>string oid = 4;</code>
       */
      public Builder setOidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        oid_ = value;
        onChanged();
        return this;
      }

      private Object id_ = "";
      /**
       * <pre>
       *当前消息id  可以为空
       * </pre>
       *
       * <code>string id = 5;</code>
       */
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *当前消息id  可以为空
       * </pre>
       *
       * <code>string id = 5;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *当前消息id  可以为空
       * </pre>
       *
       * <code>string id = 5;</code>
       */
      public Builder setId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当前消息id  可以为空
       * </pre>
       *
       * <code>string id = 5;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当前消息id  可以为空
       * </pre>
       *
       * <code>string id = 5;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private Object mucId_ = "";
      /**
       * <pre>
       *群id
       * </pre>
       *
       * <code>string mucId = 6;</code>
       */
      public String getMucId() {
        Object ref = mucId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          mucId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *群id
       * </pre>
       *
       * <code>string mucId = 6;</code>
       */
      public com.google.protobuf.ByteString
          getMucIdBytes() {
        Object ref = mucId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          mucId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *群id
       * </pre>
       *
       * <code>string mucId = 6;</code>
       */
      public Builder setMucId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mucId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群id
       * </pre>
       *
       * <code>string mucId = 6;</code>
       */
      public Builder clearMucId() {
        
        mucId_ = getDefaultInstance().getMucId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群id
       * </pre>
       *
       * <code>string mucId = 6;</code>
       */
      public Builder setMucIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mucId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ReadedMessage)
    }

    // @@protoc_insertion_point(class_scope:ReadedMessage)
    private static final ReadedMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ReadedMessage();
    }

    public static ReadedMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReadedMessage>
        PARSER = new com.google.protobuf.AbstractParser<ReadedMessage>() {
      public ReadedMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReadedMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReadedMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ReadedMessage> getParserForType() {
      return PARSER;
    }

    public ReadedMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReadedMessageListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReadedMessageList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 消息id
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    String getId();
    /**
     * <pre>
     * 消息id
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>repeated .ReadedMessage readedList = 2;</code>
     */
    java.util.List<ReadedMessage>
        getReadedListList();
    /**
     * <code>repeated .ReadedMessage readedList = 2;</code>
     */
    ReadedMessage getReadedList(int index);
    /**
     * <code>repeated .ReadedMessage readedList = 2;</code>
     */
    int getReadedListCount();
    /**
     * <code>repeated .ReadedMessage readedList = 2;</code>
     */
    java.util.List<? extends ReadedMessageOrBuilder>
        getReadedListOrBuilderList();
    /**
     * <code>repeated .ReadedMessage readedList = 2;</code>
     */
    ReadedMessageOrBuilder getReadedListOrBuilder(
        int index);

    /**
     * <pre>
     *已读消息类型  PRIVATE_CHAT(16),  //单聊    	GROUP_CHAT(17),  //群聊
     * </pre>
     *
     * <code>int32 cmd = 3;</code>
     */
    int getCmd();

    /**
     * <pre>
     *消息阅读时间
     * </pre>
     *
     * <code>int64 readTime = 4;</code>
     */
    long getReadTime();
  }
  /**
   * Protobuf type {@code ReadedMessageList}
   */
  public  static final class ReadedMessageList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ReadedMessageList)
      ReadedMessageListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReadedMessageList.newBuilder() to construct.
    private ReadedMessageList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReadedMessageList() {
      id_ = "";
      readedList_ = java.util.Collections.emptyList();
      cmd_ = 0;
      readTime_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReadedMessageList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                readedList_ = new java.util.ArrayList<ReadedMessage>();
                mutable_bitField0_ |= 0x00000002;
              }
              readedList_.add(
                  input.readMessage(ReadedMessage.parser(), extensionRegistry));
              break;
            }
            case 24: {

              cmd_ = input.readInt32();
              break;
            }
            case 32: {

              readTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          readedList_ = java.util.Collections.unmodifiableList(readedList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ReadAck.internal_static_ReadedMessageList_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ReadAck.internal_static_ReadedMessageList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ReadedMessageList.class, Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile Object id_;
    /**
     * <pre>
     * 消息id
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 消息id
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int READEDLIST_FIELD_NUMBER = 2;
    private java.util.List<ReadedMessage> readedList_;
    /**
     * <code>repeated .ReadedMessage readedList = 2;</code>
     */
    public java.util.List<ReadedMessage> getReadedListList() {
      return readedList_;
    }
    /**
     * <code>repeated .ReadedMessage readedList = 2;</code>
     */
    public java.util.List<? extends ReadedMessageOrBuilder>
        getReadedListOrBuilderList() {
      return readedList_;
    }
    /**
     * <code>repeated .ReadedMessage readedList = 2;</code>
     */
    public int getReadedListCount() {
      return readedList_.size();
    }
    /**
     * <code>repeated .ReadedMessage readedList = 2;</code>
     */
    public ReadedMessage getReadedList(int index) {
      return readedList_.get(index);
    }
    /**
     * <code>repeated .ReadedMessage readedList = 2;</code>
     */
    public ReadedMessageOrBuilder getReadedListOrBuilder(
        int index) {
      return readedList_.get(index);
    }

    public static final int CMD_FIELD_NUMBER = 3;
    private int cmd_;
    /**
     * <pre>
     *已读消息类型  PRIVATE_CHAT(16),  //单聊    	GROUP_CHAT(17),  //群聊
     * </pre>
     *
     * <code>int32 cmd = 3;</code>
     */
    public int getCmd() {
      return cmd_;
    }

    public static final int READTIME_FIELD_NUMBER = 4;
    private long readTime_;
    /**
     * <pre>
     *消息阅读时间
     * </pre>
     *
     * <code>int64 readTime = 4;</code>
     */
    public long getReadTime() {
      return readTime_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      for (int i = 0; i < readedList_.size(); i++) {
        output.writeMessage(2, readedList_.get(i));
      }
      if (cmd_ != 0) {
        output.writeInt32(3, cmd_);
      }
      if (readTime_ != 0L) {
        output.writeInt64(4, readTime_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      for (int i = 0; i < readedList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, readedList_.get(i));
      }
      if (cmd_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, cmd_);
      }
      if (readTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, readTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ReadedMessageList)) {
        return super.equals(obj);
      }
      ReadedMessageList other = (ReadedMessageList) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getReadedListList()
          .equals(other.getReadedListList());
      result = result && (getCmd()
          == other.getCmd());
      result = result && (getReadTime()
          == other.getReadTime());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      if (getReadedListCount() > 0) {
        hash = (37 * hash) + READEDLIST_FIELD_NUMBER;
        hash = (53 * hash) + getReadedListList().hashCode();
      }
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + getCmd();
      hash = (37 * hash) + READTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getReadTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ReadedMessageList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReadedMessageList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReadedMessageList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReadedMessageList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReadedMessageList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReadedMessageList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReadedMessageList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ReadedMessageList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ReadedMessageList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ReadedMessageList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ReadedMessageList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ReadedMessageList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ReadedMessageList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReadedMessageList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReadedMessageList)
        ReadedMessageListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ReadAck.internal_static_ReadedMessageList_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ReadAck.internal_static_ReadedMessageList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ReadedMessageList.class, Builder.class);
      }

      // Construct using com.fingerchat.proto.message.ReadAck.ReadedMessageList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getReadedListFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";

        if (readedListBuilder_ == null) {
          readedList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          readedListBuilder_.clear();
        }
        cmd_ = 0;

        readTime_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ReadAck.internal_static_ReadedMessageList_descriptor;
      }

      public ReadedMessageList getDefaultInstanceForType() {
        return ReadedMessageList.getDefaultInstance();
      }

      public ReadedMessageList build() {
        ReadedMessageList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ReadedMessageList buildPartial() {
        ReadedMessageList result = new ReadedMessageList(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        if (readedListBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            readedList_ = java.util.Collections.unmodifiableList(readedList_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.readedList_ = readedList_;
        } else {
          result.readedList_ = readedListBuilder_.build();
        }
        result.cmd_ = cmd_;
        result.readTime_ = readTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ReadedMessageList) {
          return mergeFrom((ReadedMessageList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ReadedMessageList other) {
        if (other == ReadedMessageList.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (readedListBuilder_ == null) {
          if (!other.readedList_.isEmpty()) {
            if (readedList_.isEmpty()) {
              readedList_ = other.readedList_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureReadedListIsMutable();
              readedList_.addAll(other.readedList_);
            }
            onChanged();
          }
        } else {
          if (!other.readedList_.isEmpty()) {
            if (readedListBuilder_.isEmpty()) {
              readedListBuilder_.dispose();
              readedListBuilder_ = null;
              readedList_ = other.readedList_;
              bitField0_ = (bitField0_ & ~0x00000002);
              readedListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getReadedListFieldBuilder() : null;
            } else {
              readedListBuilder_.addAllMessages(other.readedList_);
            }
          }
        }
        if (other.getCmd() != 0) {
          setCmd(other.getCmd());
        }
        if (other.getReadTime() != 0L) {
          setReadTime(other.getReadTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ReadedMessageList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ReadedMessageList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object id_ = "";
      /**
       * <pre>
       * 消息id
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 消息id
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 消息id
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public Builder setId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息id
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息id
       * </pre>
       *
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.util.List<ReadedMessage> readedList_ =
        java.util.Collections.emptyList();
      private void ensureReadedListIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          readedList_ = new java.util.ArrayList<ReadedMessage>(readedList_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ReadedMessage, ReadedMessage.Builder, ReadedMessageOrBuilder> readedListBuilder_;

      /**
       * <code>repeated .ReadedMessage readedList = 2;</code>
       */
      public java.util.List<ReadedMessage> getReadedListList() {
        if (readedListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(readedList_);
        } else {
          return readedListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ReadedMessage readedList = 2;</code>
       */
      public int getReadedListCount() {
        if (readedListBuilder_ == null) {
          return readedList_.size();
        } else {
          return readedListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ReadedMessage readedList = 2;</code>
       */
      public ReadedMessage getReadedList(int index) {
        if (readedListBuilder_ == null) {
          return readedList_.get(index);
        } else {
          return readedListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ReadedMessage readedList = 2;</code>
       */
      public Builder setReadedList(
          int index, ReadedMessage value) {
        if (readedListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReadedListIsMutable();
          readedList_.set(index, value);
          onChanged();
        } else {
          readedListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ReadedMessage readedList = 2;</code>
       */
      public Builder setReadedList(
          int index, ReadedMessage.Builder builderForValue) {
        if (readedListBuilder_ == null) {
          ensureReadedListIsMutable();
          readedList_.set(index, builderForValue.build());
          onChanged();
        } else {
          readedListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ReadedMessage readedList = 2;</code>
       */
      public Builder addReadedList(ReadedMessage value) {
        if (readedListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReadedListIsMutable();
          readedList_.add(value);
          onChanged();
        } else {
          readedListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ReadedMessage readedList = 2;</code>
       */
      public Builder addReadedList(
          int index, ReadedMessage value) {
        if (readedListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReadedListIsMutable();
          readedList_.add(index, value);
          onChanged();
        } else {
          readedListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ReadedMessage readedList = 2;</code>
       */
      public Builder addReadedList(
          ReadedMessage.Builder builderForValue) {
        if (readedListBuilder_ == null) {
          ensureReadedListIsMutable();
          readedList_.add(builderForValue.build());
          onChanged();
        } else {
          readedListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ReadedMessage readedList = 2;</code>
       */
      public Builder addReadedList(
          int index, ReadedMessage.Builder builderForValue) {
        if (readedListBuilder_ == null) {
          ensureReadedListIsMutable();
          readedList_.add(index, builderForValue.build());
          onChanged();
        } else {
          readedListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ReadedMessage readedList = 2;</code>
       */
      public Builder addAllReadedList(
          Iterable<? extends ReadedMessage> values) {
        if (readedListBuilder_ == null) {
          ensureReadedListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, readedList_);
          onChanged();
        } else {
          readedListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ReadedMessage readedList = 2;</code>
       */
      public Builder clearReadedList() {
        if (readedListBuilder_ == null) {
          readedList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          readedListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ReadedMessage readedList = 2;</code>
       */
      public Builder removeReadedList(int index) {
        if (readedListBuilder_ == null) {
          ensureReadedListIsMutable();
          readedList_.remove(index);
          onChanged();
        } else {
          readedListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ReadedMessage readedList = 2;</code>
       */
      public ReadedMessage.Builder getReadedListBuilder(
          int index) {
        return getReadedListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ReadedMessage readedList = 2;</code>
       */
      public ReadedMessageOrBuilder getReadedListOrBuilder(
          int index) {
        if (readedListBuilder_ == null) {
          return readedList_.get(index);  } else {
          return readedListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ReadedMessage readedList = 2;</code>
       */
      public java.util.List<? extends ReadedMessageOrBuilder>
           getReadedListOrBuilderList() {
        if (readedListBuilder_ != null) {
          return readedListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(readedList_);
        }
      }
      /**
       * <code>repeated .ReadedMessage readedList = 2;</code>
       */
      public ReadedMessage.Builder addReadedListBuilder() {
        return getReadedListFieldBuilder().addBuilder(
            ReadedMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .ReadedMessage readedList = 2;</code>
       */
      public ReadedMessage.Builder addReadedListBuilder(
          int index) {
        return getReadedListFieldBuilder().addBuilder(
            index, ReadedMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .ReadedMessage readedList = 2;</code>
       */
      public java.util.List<ReadedMessage.Builder>
           getReadedListBuilderList() {
        return getReadedListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ReadedMessage, ReadedMessage.Builder, ReadedMessageOrBuilder>
          getReadedListFieldBuilder() {
        if (readedListBuilder_ == null) {
          readedListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ReadedMessage, ReadedMessage.Builder, ReadedMessageOrBuilder>(
                  readedList_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          readedList_ = null;
        }
        return readedListBuilder_;
      }

      private int cmd_ ;
      /**
       * <pre>
       *已读消息类型  PRIVATE_CHAT(16),  //单聊    	GROUP_CHAT(17),  //群聊
       * </pre>
       *
       * <code>int32 cmd = 3;</code>
       */
      public int getCmd() {
        return cmd_;
      }
      /**
       * <pre>
       *已读消息类型  PRIVATE_CHAT(16),  //单聊    	GROUP_CHAT(17),  //群聊
       * </pre>
       *
       * <code>int32 cmd = 3;</code>
       */
      public Builder setCmd(int value) {
        
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *已读消息类型  PRIVATE_CHAT(16),  //单聊    	GROUP_CHAT(17),  //群聊
       * </pre>
       *
       * <code>int32 cmd = 3;</code>
       */
      public Builder clearCmd() {
        
        cmd_ = 0;
        onChanged();
        return this;
      }

      private long readTime_ ;
      /**
       * <pre>
       *消息阅读时间
       * </pre>
       *
       * <code>int64 readTime = 4;</code>
       */
      public long getReadTime() {
        return readTime_;
      }
      /**
       * <pre>
       *消息阅读时间
       * </pre>
       *
       * <code>int64 readTime = 4;</code>
       */
      public Builder setReadTime(long value) {
        
        readTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息阅读时间
       * </pre>
       *
       * <code>int64 readTime = 4;</code>
       */
      public Builder clearReadTime() {
        
        readTime_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ReadedMessageList)
    }

    // @@protoc_insertion_point(class_scope:ReadedMessageList)
    private static final ReadedMessageList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ReadedMessageList();
    }

    public static ReadedMessageList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReadedMessageList>
        PARSER = new com.google.protobuf.AbstractParser<ReadedMessageList>() {
      public ReadedMessageList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReadedMessageList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReadedMessageList> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ReadedMessageList> getParserForType() {
      return PARSER;
    }

    public ReadedMessageList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReadedMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReadedMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReadedMessageList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReadedMessageList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rreadack.proto\"b\n\rReadedMessage\022\017\n\007sync" +
      "hro\030\001 \001(\005\022\n\n\002to\030\002 \001(\t\022\014\n\004from\030\003 \001(\t\022\013\n\003o" +
      "id\030\004 \001(\t\022\n\n\002id\030\005 \001(\t\022\r\n\005mucId\030\006 \001(\t\"b\n\021R" +
      "eadedMessageList\022\n\n\002id\030\001 \001(\t\022\"\n\nreadedLi" +
      "st\030\002 \003(\0132\016.ReadedMessage\022\013\n\003cmd\030\003 \001(\005\022\020\n" +
      "\010readTime\030\004 \001(\003B\'\n\034com.fingerchat.proto." +
      "messageB\007ReadAckb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ReadedMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ReadedMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReadedMessage_descriptor,
        new String[] { "Synchro", "To", "From", "Oid", "Id", "MucId", });
    internal_static_ReadedMessageList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ReadedMessageList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReadedMessageList_descriptor,
        new String[] { "Id", "ReadedList", "Cmd", "ReadTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
