package com.lensim.fingerchat.hexmeet.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "REST_CALL_RECORD_".
 */
public class RestCallRecord_ {

  private Long id;
  private Integer fromSipNum;
  private Integer toSipNum;
  private Boolean isVideoCall;
  private Long startTime;
  private Long duration;

  public RestCallRecord_() {
  }

  public RestCallRecord_(Long id) {
    this.id = id;
  }

  public RestCallRecord_(Long id, Integer fromSipNum, Integer toSipNum, Boolean isVideoCall, Long startTime, Long duration) {
    this.id = id;
    this.fromSipNum = fromSipNum;
    this.toSipNum = toSipNum;
    this.isVideoCall = isVideoCall;
    this.startTime = startTime;
    this.duration = duration;
  }

  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Integer getFromSipNum() {
    return fromSipNum;
  }

  public void setFromSipNum(Integer fromSipNum) {
    this.fromSipNum = fromSipNum;
  }

  public Integer getToSipNum() {
    return toSipNum;
  }

  public void setToSipNum(Integer toSipNum) {
    this.toSipNum = toSipNum;
  }

  public Boolean getIsVideoCall() {
    return isVideoCall;
  }

  public void setIsVideoCall(Boolean isVideoCall) {
    this.isVideoCall = isVideoCall;
  }

  public Long getStartTime() {
    return startTime;
  }

  public void setStartTime(Long startTime) {
    this.startTime = startTime;
  }

  public Long getDuration() {
    return duration;
  }

  public void setDuration(Long duration) {
    this.duration = duration;
  }

}
