package com.lensim.fingerchat.hexmeet.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "REST_CONTACT_".
 */
public class RestContact_Dao extends AbstractDao<RestContact_, Long> {

  public static final String TABLENAME = "REST_CONTACT_";

  /**
   * Properties of entity RestContact_.<br/>
   * Can be used for QueryBuilder and for referencing column names.
   */
  public static class Properties {

    public final static Property Id = new Property(0, Long.class, "id", true, "_id");
    public final static Property Name = new Property(1, String.class, "name", false, "NAME");
    public final static Property OwnerId = new Property(2, Integer.class, "ownerId", false, "OWNER_ID");
    public final static Property Email = new Property(3, String.class, "email", false, "EMAIL");
    public final static Property Telephone = new Property(4, String.class, "telephone", false, "TELEPHONE");
    public final static Property Cellphone = new Property(5, String.class, "cellphone", false, "CELLPHONE");
    public final static Property UserId = new Property(6, Integer.class, "userId", false, "USER_ID");
    public final static Property LastModifiedTime = new Property(7, Long.class, "lastModifiedTime", false, "LAST_MODIFIED_TIME");
    public final static Property UserName = new Property(8, String.class, "userName", false, "USER_NAME");
    public final static Property OrgName = new Property(9, String.class, "orgName", false, "ORG_NAME");
    public final static Property H323ConfNumber = new Property(10, String.class, "h323ConfNumber", false, "H323_CONF_NUMBER");
    public final static Property SipConfNumber = new Property(11, String.class, "sipConfNumber", false, "SIP_CONF_NUMBER");
    public final static Property Pstn = new Property(12, String.class, "pstn", false, "PSTN");
    public final static Property CallNumber = new Property(13, String.class, "callNumber", false, "CALL_NUMBER");
    public final static Property ImageURL = new Property(14, String.class, "imageURL", false, "IMAGE_URL");
    public final static Property Status = new Property(15, String.class, "status", false, "STATUS");
  }

  ;


  public RestContact_Dao(DaoConfig config) {
    super(config);
  }

  public RestContact_Dao(DaoConfig config, DaoSession daoSession) {
    super(config, daoSession);
  }

  /**
   * Creates the underlying database table.
   */
  public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
    String constraint = ifNotExists ? "IF NOT EXISTS " : "";
    db.execSQL("CREATE TABLE " + constraint + "\"REST_CONTACT_\" (" + //
        "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
        "\"NAME\" TEXT," + // 1: name
        "\"OWNER_ID\" INTEGER," + // 2: ownerId
        "\"EMAIL\" TEXT," + // 3: email
        "\"TELEPHONE\" TEXT," + // 4: telephone
        "\"CELLPHONE\" TEXT," + // 5: cellphone
        "\"USER_ID\" INTEGER," + // 6: userId
        "\"LAST_MODIFIED_TIME\" INTEGER," + // 7: lastModifiedTime
        "\"USER_NAME\" TEXT," + // 8: userName
        "\"ORG_NAME\" TEXT," + // 9: orgName
        "\"H323_CONF_NUMBER\" TEXT," + // 10: h323ConfNumber
        "\"SIP_CONF_NUMBER\" TEXT," + // 11: sipConfNumber
        "\"PSTN\" TEXT," + // 12: pstn
        "\"CALL_NUMBER\" TEXT," + // 13: callNumber
        "\"IMAGE_URL\" TEXT," + // 14: imageURL
        "\"STATUS\" TEXT);"); // 15: status
  }

  /**
   * Drops the underlying database table.
   */
  public static void dropTable(SQLiteDatabase db, boolean ifExists) {
    String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"REST_CONTACT_\"";
    db.execSQL(sql);
  }

  /**
   * @inheritdoc
   */
  @Override
  protected void bindValues(SQLiteStatement stmt, RestContact_ entity) {
    stmt.clearBindings();

    Long id = entity.getId();
    if (id != null) {
      stmt.bindLong(1, id);
    }

    String name = entity.getName();
    if (name != null) {
      stmt.bindString(2, name);
    }

    Integer ownerId = entity.getOwnerId();
    if (ownerId != null) {
      stmt.bindLong(3, ownerId);
    }

    String email = entity.getEmail();
    if (email != null) {
      stmt.bindString(4, email);
    }

    String telephone = entity.getTelephone();
    if (telephone != null) {
      stmt.bindString(5, telephone);
    }

    String cellphone = entity.getCellphone();
    if (cellphone != null) {
      stmt.bindString(6, cellphone);
    }

    Integer userId = entity.getUserId();
    if (userId != null) {
      stmt.bindLong(7, userId);
    }

    Long lastModifiedTime = entity.getLastModifiedTime();
    if (lastModifiedTime != null) {
      stmt.bindLong(8, lastModifiedTime);
    }

    String userName = entity.getUserName();
    if (userName != null) {
      stmt.bindString(9, userName);
    }

    String orgName = entity.getOrgName();
    if (orgName != null) {
      stmt.bindString(10, orgName);
    }

    String h323ConfNumber = entity.getH323ConfNumber();
    if (h323ConfNumber != null) {
      stmt.bindString(11, h323ConfNumber);
    }

    String sipConfNumber = entity.getSipConfNumber();
    if (sipConfNumber != null) {
      stmt.bindString(12, sipConfNumber);
    }

    String pstn = entity.getPstn();
    if (pstn != null) {
      stmt.bindString(13, pstn);
    }

    String callNumber = entity.getCallNumber();
    if (callNumber != null) {
      stmt.bindString(14, callNumber);
    }

    String imageURL = entity.getImageURL();
    if (imageURL != null) {
      stmt.bindString(15, imageURL);
    }

    String status = entity.getStatus();
    if (status != null) {
      stmt.bindString(16, status);
    }
  }

  /**
   * @inheritdoc
   */
  @Override
  public Long readKey(Cursor cursor, int offset) {
    return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
  }

  /**
   * @inheritdoc
   */
  @Override
  public RestContact_ readEntity(Cursor cursor, int offset) {
    RestContact_ entity = new RestContact_( //
        cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
        cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
        cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // ownerId
        cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // email
        cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // telephone
        cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // cellphone
        cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // userId
        cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7), // lastModifiedTime
        cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // userName
        cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // orgName
        cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // h323ConfNumber
        cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // sipConfNumber
        cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // pstn
        cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // callNumber
        cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // imageURL
        cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15) // status
    );
    return entity;
  }

  /**
   * @inheritdoc
   */
  @Override
  public void readEntity(Cursor cursor, RestContact_ entity, int offset) {
    entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
    entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
    entity.setOwnerId(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
    entity.setEmail(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
    entity.setTelephone(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
    entity.setCellphone(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
    entity.setUserId(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
    entity.setLastModifiedTime(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
    entity.setUserName(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
    entity.setOrgName(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
    entity.setH323ConfNumber(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
    entity.setSipConfNumber(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
    entity.setPstn(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
    entity.setCallNumber(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
    entity.setImageURL(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
    entity.setStatus(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
  }

  /**
   * @inheritdoc
   */
  @Override
  protected Long updateKeyAfterInsert(RestContact_ entity, long rowId) {
    entity.setId(rowId);
    return rowId;
  }

  /**
   * @inheritdoc
   */
  @Override
  public Long getKey(RestContact_ entity) {
    if (entity != null) {
      return entity.getId();
    } else {
      return null;
    }
  }

  /**
   * @inheritdoc
   */
  @Override
  protected boolean isEntityUpdateable() {
    return true;
  }

}
