package com.lensim.fingerchat.hexmeet.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "REST_ENDPOINT_".
 */
public class RestEndpoint_ {

  private Long id;
  private String type;
  private String name;
  private String ip;
  private Boolean available;
  private Integer orgId;
  private String orgName;
  private Integer unitId;
  private String unitName;
  private Boolean inPrimaryVS;
  private Integer primaryVSSortIndex;
  private Boolean inSecondaryVS;
  private Integer secondaryVSSortIndex;
  private Integer sortIndex;
  private String e164;
  private String callType;
  private String callNumber;
  private String outwardType;
  private Boolean master;
  private String sipUrl;
  private String deviceStatus;
  private String adminId;
  private String adminPassword;
  private String deviceName;
  private String description;
  private String serialNumber;
  private String softwareVersion;
  private Integer callSpeed;
  private String contact;
  private String contactEmail;
  private String contactPhone;
  private Integer userCapacity;
  private String imageURL;

  public RestEndpoint_() {
  }

  public RestEndpoint_(Long id) {
    this.id = id;
  }

  public RestEndpoint_(Long id, String type, String name, String ip, Boolean available, Integer orgId, String orgName, Integer unitId, String unitName, Boolean inPrimaryVS, Integer primaryVSSortIndex, Boolean inSecondaryVS, Integer secondaryVSSortIndex, Integer sortIndex, String e164,
      String callType, String callNumber, String outwardType, Boolean master, String sipUrl, String deviceStatus, String adminId, String adminPassword, String deviceName, String description, String serialNumber, String softwareVersion, Integer callSpeed, String contact, String contactEmail,
      String contactPhone, Integer userCapacity, String imageURL) {
    this.id = id;
    this.type = type;
    this.name = name;
    this.ip = ip;
    this.available = available;
    this.orgId = orgId;
    this.orgName = orgName;
    this.unitId = unitId;
    this.unitName = unitName;
    this.inPrimaryVS = inPrimaryVS;
    this.primaryVSSortIndex = primaryVSSortIndex;
    this.inSecondaryVS = inSecondaryVS;
    this.secondaryVSSortIndex = secondaryVSSortIndex;
    this.sortIndex = sortIndex;
    this.e164 = e164;
    this.callType = callType;
    this.callNumber = callNumber;
    this.outwardType = outwardType;
    this.master = master;
    this.sipUrl = sipUrl;
    this.deviceStatus = deviceStatus;
    this.adminId = adminId;
    this.adminPassword = adminPassword;
    this.deviceName = deviceName;
    this.description = description;
    this.serialNumber = serialNumber;
    this.softwareVersion = softwareVersion;
    this.callSpeed = callSpeed;
    this.contact = contact;
    this.contactEmail = contactEmail;
    this.contactPhone = contactPhone;
    this.userCapacity = userCapacity;
    this.imageURL = imageURL;
  }

  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getIp() {
    return ip;
  }

  public void setIp(String ip) {
    this.ip = ip;
  }

  public Boolean getAvailable() {
    return available;
  }

  public void setAvailable(Boolean available) {
    this.available = available;
  }

  public Integer getOrgId() {
    return orgId;
  }

  public void setOrgId(Integer orgId) {
    this.orgId = orgId;
  }

  public String getOrgName() {
    return orgName;
  }

  public void setOrgName(String orgName) {
    this.orgName = orgName;
  }

  public Integer getUnitId() {
    return unitId;
  }

  public void setUnitId(Integer unitId) {
    this.unitId = unitId;
  }

  public String getUnitName() {
    return unitName;
  }

  public void setUnitName(String unitName) {
    this.unitName = unitName;
  }

  public Boolean getInPrimaryVS() {
    return inPrimaryVS;
  }

  public void setInPrimaryVS(Boolean inPrimaryVS) {
    this.inPrimaryVS = inPrimaryVS;
  }

  public Integer getPrimaryVSSortIndex() {
    return primaryVSSortIndex;
  }

  public void setPrimaryVSSortIndex(Integer primaryVSSortIndex) {
    this.primaryVSSortIndex = primaryVSSortIndex;
  }

  public Boolean getInSecondaryVS() {
    return inSecondaryVS;
  }

  public void setInSecondaryVS(Boolean inSecondaryVS) {
    this.inSecondaryVS = inSecondaryVS;
  }

  public Integer getSecondaryVSSortIndex() {
    return secondaryVSSortIndex;
  }

  public void setSecondaryVSSortIndex(Integer secondaryVSSortIndex) {
    this.secondaryVSSortIndex = secondaryVSSortIndex;
  }

  public Integer getSortIndex() {
    return sortIndex;
  }

  public void setSortIndex(Integer sortIndex) {
    this.sortIndex = sortIndex;
  }

  public String getE164() {
    return e164;
  }

  public void setE164(String e164) {
    this.e164 = e164;
  }

  public String getCallType() {
    return callType;
  }

  public void setCallType(String callType) {
    this.callType = callType;
  }

  public String getCallNumber() {
    return callNumber;
  }

  public void setCallNumber(String callNumber) {
    this.callNumber = callNumber;
  }

  public String getOutwardType() {
    return outwardType;
  }

  public void setOutwardType(String outwardType) {
    this.outwardType = outwardType;
  }

  public Boolean getMaster() {
    return master;
  }

  public void setMaster(Boolean master) {
    this.master = master;
  }

  public String getSipUrl() {
    return sipUrl;
  }

  public void setSipUrl(String sipUrl) {
    this.sipUrl = sipUrl;
  }

  public String getDeviceStatus() {
    return deviceStatus;
  }

  public void setDeviceStatus(String deviceStatus) {
    this.deviceStatus = deviceStatus;
  }

  public String getAdminId() {
    return adminId;
  }

  public void setAdminId(String adminId) {
    this.adminId = adminId;
  }

  public String getAdminPassword() {
    return adminPassword;
  }

  public void setAdminPassword(String adminPassword) {
    this.adminPassword = adminPassword;
  }

  public String getDeviceName() {
    return deviceName;
  }

  public void setDeviceName(String deviceName) {
    this.deviceName = deviceName;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getSerialNumber() {
    return serialNumber;
  }

  public void setSerialNumber(String serialNumber) {
    this.serialNumber = serialNumber;
  }

  public String getSoftwareVersion() {
    return softwareVersion;
  }

  public void setSoftwareVersion(String softwareVersion) {
    this.softwareVersion = softwareVersion;
  }

  public Integer getCallSpeed() {
    return callSpeed;
  }

  public void setCallSpeed(Integer callSpeed) {
    this.callSpeed = callSpeed;
  }

  public String getContact() {
    return contact;
  }

  public void setContact(String contact) {
    this.contact = contact;
  }

  public String getContactEmail() {
    return contactEmail;
  }

  public void setContactEmail(String contactEmail) {
    this.contactEmail = contactEmail;
  }

  public String getContactPhone() {
    return contactPhone;
  }

  public void setContactPhone(String contactPhone) {
    this.contactPhone = contactPhone;
  }

  public Integer getUserCapacity() {
    return userCapacity;
  }

  public void setUserCapacity(Integer userCapacity) {
    this.userCapacity = userCapacity;
  }

  public String getImageURL() {
    return imageURL;
  }

  public void setImageURL(String imageURL) {
    this.imageURL = imageURL;
  }

}
